### ISSUE TITLE
Formatting Date from CoreData

### ISSUE THREAD

**Issue by JamesCosgrove** [rbevans-ugh/weida#1]
In your `StatItem.swift` file, you can create a computed property inside the `StatItem` class which references `createdAt` as follows:

```
public class StatItem:NSManagedObject, Identifiable {
    @NSManaged public var createdAt:Date?
    @NSManaged public var lift:String?
    @NSManaged public var weight:String?
    
    var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = ""
        return formatter.string(from: createdAt ?? Date())
    }
}
```

You can change the empty string on the `formatter.dateFormat` line to `"MMM d, yyyy"` or any of the others [found here](https://nsdateformatter.com).

In the last line where the string is returned, the presence of `createdAt` is tested and if it doesn't exist the current date is used. This is necessary as CoreDate stores dates as optional by default. It is good practice to do this for all parameters in one place and then read their formatted values like so:

```
public class StatItem:NSManagedObject, Identifiable {
    @NSManaged public var createdAt:Date?
    @NSManaged public var lift:String?
    @NSManaged public var weight:String?
    
    var formattedDate: String {
        let formatter = DateFormatter()
        formatter.dateFormat = ""
        return formatter.string(from: createdAt ?? Date())
    }
    
    var formattedLift: String {
        return lift ?? "No Lift Found" //Or some default value
    }
    
    var formattedWeight: String {
        return weight ?? "No Weight Found" //Or some default value
    }
}
```

**Comment by arbyruns** [comment]
Thanks! Do I need to declare `let dateString = formatter.string(from: createdAt!)`  in `formattedDate`?

**Comment by JamesCosgrove** [comment]
The variable `formattedDate` is now effectively the same as `dateString` so if you wanted to you could just rename `formattedDate` to `dateString` so you can continue using it in the rest of your code.

**Comment by arbyruns** [comment]
That's really weird.  Earlier I tried using `formattedDate` and the compiler didn't like it, but now it works.  Thanks!
